### ISSUE TITLE
Network request failed running native iOS

### ISSUE THREAD

**Issue by justinr1234** [codefoundries/UniversalRelayBoilerplate#11]
I have swapped out all the IP addresses and tried modifying the really network layer to match the exact same as the web app version. I keep getting a yellow "Network request failed" bar at the bottom of the mobile with s blank white screen after the js bundle has loaded. This error is generated by the fetch library being used internally by Relay. I'm actually not quite sure how to really debug this one. I've verified I'm on the same wifi, and tried both simulator and on device. Any ideas what I can try? I'll mess with it more next time I get a chance.

**Comment by thelordoftheboards** [comment]
Did you try the `npm run update-ip` or you made the change manually? Did you change the HOST in the .env file also?

**Comment by justinr1234** [comment]
I won't be able to test for a bit as my priorities have shifted off working on this architecture at the moment. I'll get back to this when I get a chance.

**Comment by thelordoftheboards** [comment]
Thank you. I will keep the issue open till I get the entire stack to with with Relay 0.8, then I will test changing the IP. If it does not work I will work on a fix, if it does I will close the issue and you can try with the new version and re-open if necessary.

**Comment by thelordoftheboards** [comment]
Using 'npm run update-ip' works in my case with the latest changes, so I am closing the question. If it happens with the latest release, re-open the issue.
