### ISSUE TITLE
how to resolve nested data

### ISSUE THREAD

**Issue by Rohit-cheddr** [codefoundries/UniversalRelayBoilerplate#128]
Hello!
I am having trouble resolving nested types. For instance:
```
{
  post: {
    title,
    author:{
      name
      address: {
        city
      }
    }
  }
}
```
In the above scenario, how would I resolve `author` from within the `post`? The `author` and the `post` would each have its own folder under the `units` directory. 

I can understand how this would be implemented if there were an array of authors in the post (from the examples that exist now), but how about if there is just a single author?

Edit: added a bit more information on exactly what problem i am having.

**Comment by thelordoftheboards** [comment]
What GraphQL schema are you using?

**Comment by Rohit-cheddr** [comment]
I am trying to add more of my own units to this boilerplate. The above code snippet is just to demonstrate what I am trying to do (basically nested data)

**Comment by Rohit-cheddr** [comment]
Basically, is there a "connectionFromArray" equivalent for an individual object? All of the example units are basically lists of types (ToDo, Ensayo, etc) which we use connectionFromArray to link to the ViewerFields. What if there is only one item of a given type that we need to connect?

**Comment by thelordoftheboards** [comment]
Have you looked at Compendium? Maybe that approach can work for you?

**Comment by Rohit-cheddr** [comment]
So, the CompendiumType itself is composed of "leaf" elements so each one is easy to resolve. But, what if one of its elements is, say, a single TodoType? How would the resolve function look?

```
export default new GraphQLObjectType( {
  name: 'Compendium',
  interfaces: [NodeInterface],
  isTypeOf: object => object instanceof Compendium,
  fields: {
    ...
    todo_item: { type: TodoType,  resolve: (obj) => ????? },
  },
} );
```
what would we return in the above scenario?

**Comment by Rohit-cheddr** [comment]
Would it just be:
`objectManager.getOneById('Todo', obj.todo_item_id).then((todoObj) => todoObj)`?

**Comment by Rohit-cheddr** [comment]
The more I think about it, i think my question can be boiled down to this:
How do we handle one-to-one relationships?

All the examples show a one-to-many relationship between the viewer and the type (to-do, compendium, etc.)

**Comment by thelordoftheboards** [comment]
I am not an expert on GraphQL, so take my words with a grain of salt. I do not know of a way to model one to one relationships. One way that I can think of is to add more properties, the other one is to use one to many relationship, and only have one child.

**Comment by thelordoftheboards** [comment]
In the case of Compendium, only one item is ever created, although from the point of view of GraphQL this is a one to many relationship.

**Comment by Rohit-cheddr** [comment]
Ah, I see. I think I figured it out as well. I found where this is being done! Ensayo _ViewerFields implements both multiple as well as single. It provides a good example.
