### ISSUE TITLE
Mocking data?

### ISSUE THREAD

**Issue by Rohit-cheddr** [codefoundries/UniversalRelayBoilerplate#130]
Hello!
Is there any way to mock/dummy the data so we can test out the schema while building it?

Thanks in advance!

**Comment by thelordoftheboards** [comment]
If you use the in-memory implementation, all data are just arrays in memory. It should be easy to insert some data there.
Also, when using Cassandra, the Ensayo table is pre-populated with some data.
Would one of these two approaches work for you?

**Comment by Rohit-cheddr** [comment]
They should! I tried to add mock data directly to the in memory data
object, but when I query for it in graphiql, it says expected "Todo" but
got [Object object]. Should I actually use the objectmanager.add method?

**Comment by Rohit-cheddr** [comment]
Okay, I figured out a way that I am happy with. For anyone who wants to know how I did it, here's what I did:

* Created `mocks/mock.js` file in the graphql folder and created function: `export default function mocks(objectManager)` inside the mocks file
  * In the function, I created a todoFields object with my mock data and just called `objectManager.add('Todo', todoFields)`
* imported mocks into server.js in graphql folder and passed the objectManager instance: `mocks(objectManager)`

[casual](https://www.npmjs.com/package/casual) is a good library if you need to create realistic mock data.

Hope this helps!
