### ISSUE TITLE
Quick tips on native setup

### ISSUE THREAD

**Issue by pennyandsean** [codefoundries/UniversalRelayBoilerplate#133]
Hi there, Just getting started. What is the quick description on building the native parts.  After doing ip-update and start and build-bundle-ios-dev, do I fire up xcode and point it to the ios folder as a project.  Also with Android do I point android studio at the android folder?  (Got a bit lost in Gradle configs)

**Comment by thelordoftheboards** [comment]
I would suggest to use `npm run dev`, or `npm run dev-server` to have your GraphQL server available. After that you can use `react-native run-ios` and `react-native run-android` respectively. You do not _need_ to XCode or Android studio to build and run the projects, however you can do that too. Does that answer your question?

**Comment by pennyandsean** [comment]
Yes, thanks, I should have read the react native docs ;).  This is great project, I was looking for an example that is as modular as possible and so this is where I started.  Cheers

**Comment by thelordoftheboards** [comment]
Happy to hear that you like!
I will close the issue, if you stumble on other issues running RN please open a new one.
