### ISSUE TITLE
[webapp, server] Integration of Relax into the boilerplate

### ISSUE THREAD

**Issue by jshin47** [codefoundries/UniversalRelayBoilerplate#137]
I started seeing this error show up after I reorganized some of the project folders. And I mean, it was a big reorg. But I generally know how to deal with that aftermath. What I don't know is why I am seeing this, and what could be the relation between my actions and this result.

The specific reorg I did was to make copies of the configuration folder files into each of the corresponding root folders. I don't like that configuration folder. The distinction is too arbitrary to me.

<code> Invariant Violation: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.    at invariant (/Users/justin/Projects/Replay/node_modules/fbjs/lib/invariant.js:38:15)    at Object.RelayQL [as QL] (/Users/justin/Projects/Replay/node_modules/react-relay/lib/RelayQL.js:31:32)    at Viewer (routes.js:29:23)    at wrappedQuery (/Users/justin/Projects/Replay/node_modules/isomorphic-relay-router/node_modules/react-router-relay/lib/QueryAggregator.js:140:22)    at Object.Query (/Users/justin/Projects/Replay/node_modules/react-relay/lib/buildRQL.js:80:16)    at Object.instrumentedCallback [as Query] (/Users/justin/Projects/Replay/node_modules/react-relay/lib/RelayProfiler.js:131:40)    at /Users/justin/Projects/Replay/node_modules/react-relay/lib/getRelayQueries.js:47:49    at Array.forEach (native)    at Object.getRelayQueries (/Users/justin/Projects/Replay/node_modules/react-relay/lib/getRelayQueries.js:40:41)    at Object.instrumentedCallback [as getQueries] (/Users/justin/Projects/Replay/node_modules/react-relay/lib/RelayProfiler.js:131:40)</code>

**Comment by thelordoftheboards** [comment]
After the reorg, when you attempt to generate the schema with `npm run build-schema` are you able to generate a proper schema?

**Comment by jshin47** [comment]
Well not exactly but

I have a different question

If I could do it would you be interested in having the Relax model or parts
of it in this boilerplate?

**Comment by thelordoftheboards** [comment]
That would be very interesting! What kind of integration do you have in mind? Can you please describe it in a bit more detail?

I believe an integrated CMS could be beneficial for a wide range of projects, so as long as it runs well side by side, that would be very cool. However, my understanding is that Relax runs on Mongo, and the rest of the boilerplate runs on Cassandra. It would be a paramount requirement that the Mongo dependency can be easily removed in cases when it is not required.

**Comment by jshin47** [comment]
I missed your update, sorry.

I did the work already but I'll have to find it. Basically, there are a bunch of types in Relax. I wonder if some subset of them are a good baseline of if nothing else, examples for GraphQL.

Those types are backend by calls to MongoDB. All that boilerplate is provided by Relax.

Examples of the classes: File Upload, Page, Template, Content, 

in general, CMS-type stuff.

**Comment by thelordoftheboards** [comment]
Sounds like something very straightforward to do in this case. Maybe place it into its own separate unit?

**Comment by thelordoftheboards** [comment]
Closing at this point. Not a main focus of the project, since Relax is limited to MongoDB only. I would definitely accept a PR as long as the object types are in a separate unit, which should be trivial to do.
