### ISSUE TITLE
Use Happypack and DLL plugin

### ISSUE THREAD

**Issue by johntran** [codefoundries/UniversalRelayBoilerplate#138]
Hey there!

I've been following this project since my company is using GraphQL and Relay for our upcoming app. It came to the point where initial build times were 90 seconds and incremental was 45 seconds. After implementing https://github.com/amireh/happypack and https://github.com/webpack/docs/wiki/list-of-plugins#dllplugin, we were able to cut it down to 10 seconds initial and 4 seconds incremental for GraphQL server changes, and 300ms for React view changes.

Our webpack dev config and webpack dll config:

https://gist.github.com/johntran/6bef02d5853edc67c3ac8f4e06a60ba1

npm commands
```
  "build-dll": "webpack --config webpack.dll.js",
    "build-run": "npm run build && babel-node server/server.js",
    "dev": "npm run build-dll && nodemon --exec npm run build-run",
```

Steps to add dll plugin:
1. Create your webpack dll config
2. Add dllreferenceplugin to your webpack config
3. Insert a link to the bundle in your index.html. We use AddAssetHtmlPlugin to programmatically add it.

Reference: https://robertknight.github.io/posts/webpack-dll-plugins/

Happypack is also a bit cumbersome to install. 

1.add the package and add it to your webpack config. See lines 120-127 on webpack.dev.js.
2. Stringify your .babelrc and add it to the loader. See lines 14-57 and line 125 on webpack.dev.js.

I love this project and these additions will put this boilerplate on the next level. I've never seen a Relay project that used Happypack, so I had to discover this all by myself. 

Hopefully this all helps! I would've made a PR, but I don't have the spare time to dig in at the moment.

**Comment by thelordoftheboards** [comment]
@johntran this is awesome stuff! Definitely worth investigating! Thank you for sharing, I am swamped at the moment but whenever I get some time I definitely want to check it out. If you in the meantime make a PR, or have more examples, please do not  why away from sharing.

**Comment by thelordoftheboards** [comment]
I read a bit more about happy pack and it seems that there might be a lot of headwind, especially when trying to replace webpack in react native. I am going to close the issue since I believe at this point it is not worth trying. However, if react-native (and react-dom of course) boilerplates show up in the wild and are stable enough, the inclusion can be reconsidered. Or somebody created a PR for this repository that works well.
