### ISSUE TITLE
Profile picture does not display in logged in user menu

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#15]
![image](https://cloud.githubusercontent.com/assets/7056535/14961576/2c883eb6-104f-11e6-8d53-a2c1383b8cbe.png)

**Comment by thelordoftheboards** [comment]
I'm not sure why is that, the src parameter is passed:

![image](https://cloud.githubusercontent.com/assets/7056535/15038520/42ece0ce-1259-11e6-8cf0-e8af9938ab55.png)

Best course of action is to test with the release version of MUI 0.15 and confirm that the problem persists.

**Comment by thelordoftheboards** [comment]
Well, even with the final release of 0.15 it's still not happening.

**Comment by james0123** [comment]
Jack is back: removing or giving a (valid) value to ->  avatar: { borderColor: null } in the mui-themes folder/files (grayBlue.js etc...) files fixes the problem.

**Comment by thelordoftheboards** [comment]
@james0123 thank you I will try this right now.
