### ISSUE TITLE
[units/urb-example-*] Provide Example with Nested Relationships

### ISSUE THREAD

**Issue by tim-field** [codefoundries/UniversalRelayBoilerplate#229]
Thank you for the great work you've done on this project.

This question is related to https://github.com/codefoundries/UniversalRelayBoilerplate/issues/128 somewhat, But after reading this it's still not clear to me how relationships between models should be defined. 

Say for example if I wanted a define a relationship between Ensayos so that I could query like so.

```
query ViewerQueries {
  Viewer {
  id
  User_Locale
    Ensayos {
      edges {
        node {
          Ensayo_Title
          Ensayo_Related(first: 2) {
            Ensayo_Title
          }
        }
      }
    }
  }
}
```

Would you be able to provide an example of how relationships like this can be defined?

**Comment by thelordoftheboards** [comment]
Thank you for the kind words.
Haven't done nested in here. While this is a generic GraphQL question, nesting would likely be a common pattern. I will make it a task to add such an example here.

**Comment by thelordoftheboards** [comment]
For the time being this issue is closed due to inactivity. An example can be added once the refactoring of the repository is completed.
