### ISSUE TITLE
ESLint throwing "react/display-name" error

### ISSUE THREAD

**Issue by M1chaelTran** [codefoundries/UniversalRelayBoilerplate#233]
The following block of code is from the `RelayComponentRenderer.js` file
How could this be re-written so that it doesn't throw an error?
```
export default (moduleProps) => (Component) =>
  !Relay.isContainer(Component)
    ? Component // not a Relay container, return component itself
    : props => {
    // relay container - wrap it with renderer
    return <RelayComponentRenderer
      {...moduleProps}
      {...props}
      component={Component}
    />;
  }
```
Details on the error: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md

**Comment by thelordoftheboards** [comment]
Actually this is truly a problem with lint. Having a render function instead of a class/component is a valid construct in relay. I will try still change the code to avoid this because it is a problem for you, but I am just saying that the linter is who is in the wrong here.
