### ISSUE TITLE
[global] Run in development mode on Linux.

### ISSUE THREAD

**Issue by robrobkay51** [codefoundries/UniversalRelayBoilerplate#236]
Tried to run the project on Linux and I'm getting this error message: 'Failed at the @10.1.5 start script 'node node_modules/react-native/local-cli/cli.js start --reset-cache'. Anyone got any ideas or solutions?!

**Comment by thelordoftheboards** [comment]
@robrobkay51 after looking at the error message up close it seems it has something to do with the react-native setup. Have you tried running `npm run dev-server` and `npm run dev-webpack` separately? I am looking to isolate which of the three servers started by `npm run dev` is actually failing.

**Comment by robrobkay51** [comment]
@thelordoftheboards seems to be working now - think it was an issue with the bcrypt package (which ive now updated).

**Comment by robrobkay51** [comment]
@thelordoftheboards the react-native error message still appears though - havent had chance to play around with the boilerplate yet so not sure how much of an issue it might be..

**Comment by thelordoftheboards** [comment]
Let me know. If a PR is needed that does not break the build on other systems I would be happy to merge.

**Comment by thelordoftheboards** [comment]
I am planning to close this issue due to inactivity.

**Comment by aap82** [comment]
I just installed on Ubuntu 16.04, with node v5.1.0 and npm v3.5.0, and the web version is working just fine.
