### ISSUE TITLE
[server] Provide data flow diagram fro GraphQL and ObjectManager.

### ISSUE THREAD

**Issue by Extra-lightwill** [codefoundries/UniversalRelayBoilerplate#240]
I'm fairly new to GraphQL/Relay and I'm trying to figure out exactly how everything fits together in URB.

The front-end seems fairly self-explanatory but I'm struggling to figure out exactly what the interactions between GraphQL, the object manager, the persister (cassandra) are.

Does anyone have a data flow diagram or detailed explanation that could help?

**Comment by thelordoftheboards** [comment]
I'll try to put together something. At any rate I recommend watching the talk explaining DataLoader by @leebyron : [DataLoader – Source code walkthrough](https://www.youtube.com/watch?v=OQTnXNCDywA).

**Comment by Extra-lightwill** [comment]
@thelordoftheboards I might be being really stupid here but following the instructions for setting up Cassandra I'm getting "Keyspace system_schema does not exist" after running the` npm run setup-database` command. When you say  "Verify that the name of the database in /.env is the name of the database you want." in the dev setup docs, what exactly needs to be changed here. Cassandra is up and running on my machine locally so that isn't an issue.

**Comment by thelordoftheboards** [comment]
This is indeed poor wording. Sorry about this. The idea is that the name of the keyspace should be specified in .env, instead of the default 'urb'.
Let me delete it locally and try to re-run `npm run setup-database` with the latest version, maybe it is broken now. Used to work.

**Comment by thelordoftheboards** [comment]
Not to be that guy, but "works for me":

```bash
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.3 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> describe keyspaces;

system_traces  system_schema  system_auth  system  system_distributed

cqlsh> exit
$ npm run update-default-persister -- cassandra

> @10.1.5 update-default-persister /Users/alex/Documents/Projects/URB
> babel-node ./scripts/update-default-persister.js "cassandra"

Written: /Users/alex/Documents/Projects/URB/configuration/graphql/defaultPersister.js
$ npm run setup-database

> @10.1.5 setup-database /Users/alex/Documents/Projects/URB
> babel-node ./scripts/setup-database.js

Initializing schema
Initializing Cassandra persister - start
Table ready: logs
Table ready: User
Table ready: Compendium
Table ready: Ensayo
Table ready: ToDo
Table ready: Translaticiarum
Table ready: PrimeNumber
Initializing Cassandra persister - success
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.3 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> describe keyspaces;

urb  system_schema  system_auth  system  system_distributed  system_traces

cqlsh> use urb;
cqlsh:urb> describe tables;

"Compendium"  "Translaticiarum"  logs  "PrimeNumber"  "User"  "Ensayo"  "ToDo"
```

**Comment by Extra-lightwill** [comment]
Thanks for the quick response! Ah I see what that problem is I think. So i'd already done the above steps but when i `describe keyspaces ` in cqlsh the keyspace system_schema isnt there. so thinking it might be a problem with cassandra installation.

**Comment by thelordoftheboards** [comment]
At this point there is a lot of information online about both graphql and data loader and the value of writing yet another description of how they work together has diminished.
