### ISSUE TITLE
[units/urb-persister-cassandra] Use of SASI indexes (and possibly other data modeling techniques) in Object Manager.

### ISSUE THREAD

**Issue by Extra-lightwill** [codefoundries/UniversalRelayBoilerplate#248]
I'm just wondering, I'm new to Cassandra and from my understanding, when you are querying/mutating data, you need to create a specific table in Cassandra for that specific query/mutation e.g. Users_by_todo, Users_by_ensayo (or whatever your specific application requires).

Thinking this way, you'd have to create a new table schema for every separate query (data access method) in the application. 

Since the examples provided in URB are relatively simple and do not require this sort of back-end logic, my question is, where would exactly is best to declare `addTableSchema` for each data access method. Directly within the query/mutation or within the schema file in the model folder e.g. ToDo.schema.js?

**Comment by thelordoftheboards** [comment]
Creating additional tables is an option for sure. However, before discussing creating additional tables, have you looked into materialized views and would they work for your use cases?

http://www.datastax.com/dev/blog/new-in-cassandra-3-0-materialized-views

**Comment by thelordoftheboards** [comment]
And to answer your original question, it should be possible to define new tables with .schema.js files in the graphql folder of every unit, however ObjectManager would not know to query them. It would be cool if materialized views could be used and ObjectManager would know how to query those.
What do you think?

**Comment by thelordoftheboards** [comment]
Actually, reading your question again, in your case, wouldn't it be better to use SASI indexes?

https://docs.datastax.com/en/cql/3.3/cql/cql_using/useSASIIndex.html

**Comment by Extra-lightwill** [comment]
I think SASI indexes would satisfy some use-cases, definitely. However SASI indexes can be created on a non-collection column defined in a table - so assuming this wouldn't work for queries on entities that had attributes with collection columns.

Also, most of what I've read re Cassandra seems to suggest that de-normalization and duplication is key to the way Cassandra works. The quote below for example:

**It’s important to understand and start with entities and relationships, then continue modeling around query patterns by de-normalizing and duplicating. If this sounds confusing, make sure to go through the detailed example later in this post.** http://www.ebaytechblog.com/2012/07/16/cassandra-data-modeling-best-practices-part-1/. 

This is a bit confusing to me because using SASI indexes would mean that you would have to take a slightly revised approach to data modeling - where you have tables for things like (using the provided example) cyclist_name as opposed to having a table schema such as cyclists_by_name.

So with this in mind, I think SASI indexes are definitely helpful and fulfil some use-cases but I'm not so sure they are a comprehensive solution. 

Materialized views, however, do seem to satisfy those use cases where you're making those kinds of queries that fit the traditional Cassandra data modeling practices (1:30 onwards on this video - https://www.youtube.com/watch?v=M-UDdSQCTHQ). From what I gather, materialized views can be used as a replacement for the standard (manual) de-normalisation techniques - what do you think?

So, in response to what you said, I think it would be cool if materialized views could be used and ObjectManager could query those.

**Comment by Extra-lightwill** [comment]
I think this video (https://www.youtube.com/watch?v=jLmopfi8_l4 ) kind of sums up what Im trying to articulate - here SASI indexes are being plugged as something to be used for search functionality while materialized views are used as a better alternative to manual denormalization..

**Comment by thelordoftheboards** [comment]
To put it very succinctly, my understanding is that SASI comes to simplify the data modeling, so what required a separate table before now can be achieve with an index. I need to spend some time to very carefully study all the information above and then come up with an intelligent way of integrating it into Object Manager to be able to utilize Data Loader as underlying data retrieval mechanism.

**Comment by Extra-lightwill** [comment]
Looking at the response below, I think you need both (SASI and materialized views) for a fully-functioning, performant Cassandra app:  

"SASI sweet spots: full text search with LIMIT (100 to 10000), dense index, for 1-to-1 index (like user_email) use materialized view"

"No, even with SASI you still need a good data model to get the max perf. SASI like native 2nd index will hit many nodes"

**Comment by thelordoftheboards** [comment]
I have tested a SASI index with Cassandra 3.9 and it works like a champ. Here is the schema:

```js
defaultPersister.addTableSchema( 'Villa',
{
  fields:
  {
    id: 'uuid',
    Villa_Lat: 'double',
    Villa_Lon: 'double',
    Villa_Name: 'text',
    Villa_Description: 'text',
    Villa_IndoorArea: 'int',
    Villa_OutdoorArea: 'int',
    Villa_AmenitySwimmingPool: 'boolean',
    Villa_AmenityFountain: 'boolean',
  },
  key: [ 'id' ],
  custom_indexes: [
  {
    on: 'Villa_Name',
    using: 'org.apache.cassandra.index.sasi.SASIIndex',
    options:
    {}
  } ],
} )
```

and here is a query:

```js
    resolve: async( obj,
    {
      Villa_Name_Contains,
      ...args
    }, context,
    {
      rootValue: objectManager
    } ) =>
    {
      const arr = await objectManager.getObjectList( 'Villa',
      {
        Villa_Name:
        {
          '$like': Villa_Name_Contains + '%'
        }
      } )
      return connectionFromArray( arr, args )
    }
```

Works like a charm courtesy of [`express-cassandra` support for SASI indexes](https://github.com/masumsoft/express-cassandra/issues/43). I am closing the issue.
