### ISSUE TITLE
[webapp] Changing client side files does not trigger webpack refresh.

### ISSUE THREAD

**Issue by reactor81** [codefoundries/UniversalRelayBoilerplate#254]
I see the server restart when I edit server/*.js files..

I don't see any changes / webpack rebuilding when I run unit/*.js files or configuration/*.js files (Footer, etc).. 

Is there any type of automatic watching hooked up? (I'm on mac osx)

I thought there was hot deployment so I imagined there would be automatic watching on changes.

**Comment by reactor81** [comment]
Ah, just running webpack --watch seems to work.

**Comment by thelordoftheboards** [comment]
Question: Should I add the flag to the better scripts script for start-dev?

**Comment by reactor81** [comment]
@thelordoftheboards I think so because there is a watch for the /server files that runs.. So some users will expect the watch on the client files to also be working by default.

**Comment by thelordoftheboards** [comment]
Would you be able to PR the change you did?

**Comment by reactor81** [comment]
@thelordoftheboards 

Hmm, what I ended up doing is just running 'webpack --watch' in a seperate terminal. 

1) Terminal #1 - 'npm run dev'

2) Terminal #2 - 'webpack --watch'

**Comment by thelordoftheboards** [comment]
Interesting. There are some issues with the path in the latest version, after I wrap them up I will go ahead and re-test with your use case possibly add the watch flag. Thank you for sharing. I will keep this as an open issue for now

**Comment by thelordoftheboards** [comment]
Fixed in 11.2.1 - now `npm run dev` starts the webpack server with --watch flag.
