### ISSUE TITLE
[app] Extraneous code - 'configurePushNotifications'

### ISSUE THREAD

**Issue by jverhoeven** [codefoundries/UniversalRelayBoilerplate#270]
Hi, thanks for great boilerplate. Just pulled latest master and iOS app does not start because file ../../../units/rb-push-notifications/app/configurePushNotifications is referred to from ApplicationMainSettings.ios.js and DrawerView.js, but not checked in.

**Comment by thelordoftheboards** [comment]
Sorry, bad case of copy-paste from another project I was working on. For the time being just delete all mentions and I will fix it tomorrow.
