### ISSUE TITLE
[webapp] renderOnServer error when loading images using url require syntax.

### ISSUE THREAD

**Issue by robrobkay51** [codefoundries/UniversalRelayBoilerplate#272]
This is the error I'm getting:

`error: Server error: renderOnServer render funcion failed SyntaxError: /home/rob/Desktop/current-project/urb-project/public/profile_photos/jack.jpg: Unexpected character '�' (1:0)`

This is how I'm trying to load the image: 

```
avatar: {
      div: {
        padding: '15px 0 20px 15px',
        backgroundImage:  'url(' + require("../../../public/profile_photos/jack.jpg") + ')',
        height: 45
```

Not really sure what I'm doing wrong - I've added image loaders to webpack but hasn't solved the issue.

**Comment by thelordoftheboards** [comment]
I am not very familiar with the syntax, but at least from my RN experience I would expect something like

```js
avatar: {
      div: {
        padding: '15px 0 20px 15px',
        backgroundImage:  require("../../../public/profile_photos/jack.jpg"),
        height: 45
```

Am I totally off on this one?

**Comment by robrobkay51** [comment]
Sorry for the delayed reply. 

Yeah I think that's the correct React Native syntax but it also seems to throwing an error - the same 'unexpected character' as with the syntax listed above.

**Comment by thelordoftheboards** [comment]
@robrobkay51 is the source of the project you are working available on github?

**Comment by robrobkay51** [comment]
Yep - https://github.com/robrobkay51/blank-slate-urb 

LeftDrawer file config folder (configuration/components/webapp/LeftDrawer) - at the moment, the line causing the issue is commented out.

**Comment by thelordoftheboards** [comment]
Let me see if I can figure this one out

**Comment by robrobkay51** [comment]
Any luck with this?

**Comment by thelordoftheboards** [comment]
U fortunately I have not had a chance to work on this yet.

**Comment by robrobkay51** [comment]
If you include the image like this:

`<img src={'../../../public/profile_photos/griz.jpg'} /> `

Then manually add `require` after the app is running like this:

` <img src={require('../../../public/profile_photos/griz.jpg')} />  `

..an image loads. 

I still haven't figured it out but maybe that'll spark a solution..

**Comment by thelordoftheboards** [comment]
@robrobkay51 have you been able to resolve the issues? Did they require changes in the boilerplate? If so, and it does not affect the rest of the boilerplate in a negative way, I'd love to merge a PR.

**Comment by thelordoftheboards** [comment]
@robrobkay51 I am publishing an update with the new version of webpack, which hopefully resolves the issue. If the issue re-appears feel free to reopen.
