### ISSUE TITLE
[webapp] How to use Radium with UniversalRelayBoilerplate?

### ISSUE THREAD

**Issue by Extra-lightwill** [codefoundries/UniversalRelayBoilerplate#273]
This is a pretty stupid question but I'm trying to use Radium with this boilerplate I can't work out where to put the StyleRoot tag as described here: https://github.com/FormidableLabs/radium/tree/master/docs/api#styleroot-component ?

**Comment by Extra-lightwill** [comment]
update: i've placed it around the Chrome component and the styles are rendering correctly although I'm not sure if this is best practice

**Comment by thelordoftheboards** [comment]
@Extra-lightwill if you feel like it, please feel free to add documentation to README in case anyone else is trying to achieve the same. At this point I will close the issue, which can be reopened if further issues related to Radium appear.
