### ISSUE TITLE
[app] Consider using native navigator

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#279]
https://github.com/wix/react-native-navigation

**Comment by M1chaelTran** [comment]
Looking around on the web and React-Native fb group, a lot more people are using react-native-router-flux than react-native-navigation.

Also, react-native-navigation are going through some major refactoring.
Might be wise to wait until that all settle and more people uses it before we jump the band wagon?

**Comment by thelordoftheboards** [comment]
@M1chaelTran you are absolutely right about this. I assigned it a rainy day enhancement status. I think once they have a fully featured Android solution, it will be a good time to circle back to this one.

**Comment by thelordoftheboards** [comment]
Actually, going to just close it for now, if anybody feels overly passionate about this please reopen.
