### ISSUE TITLE
[server, webapp] Document object/DOM manipulation server-side render errors

### ISSUE THREAD

**Issue by Extra-lightwill** [codefoundries/UniversalRelayBoilerplate#282]
I've recently run into a couple of server-side errors regarding DOM manipulation methods (e.g. document.querySelector/addEventListener) a couple of times now when using external libraries.
 
example errors:

`Server error: renderOnServer render function failed TypeError: document.querySelector is not a function`

`Server error: renderOnServer render function failed TypeError: target.addEventListener is not a function`

I'm not knowledgeable enough about SSR/isomorphism to know whether this is an issue with the particular libraries I'm using or whether this is something that can be addressed within URB.. I gather that this is happening because node can't perform DOM manipulations. Any advice on how to get around these would be great?

**Comment by Extra-lightwill** [comment]
I might be way off here but would something like jsdom (https://github.com/tmpvar/jsdom) or cheerio (https://cheerio.js.org/) work for this particular issue? 

Really stuck on this one :(

**Comment by thelordoftheboards** [comment]
I had a similar problem when I wanted to integrate the graphiql as part of the menu, to be used in the rest of the application, and pass the tokens for the currently logged in user, etc. I had a similar issue with the ACE editor that graphiql is using in the background. I was not able to find a quick solution. As of now I do not know of an universal method to approach these.

**Comment by Extra-lightwill** [comment]
I've done some research and selected a few (quite a lot of!) potential solutions for your review. There's a lot of material here but I'd love to hear what seems reasonable from your perspective since you have more experience than me with SSR. I'd really love to find a solution for this sooner rather than later because I've committed to URB/isomorphism. But as you said, it does seem to be an issue that the 'Universal community' hasn't really found a definitive solution for yet. After scouring pretty much every resource on the subject, I've listed what I think are the best potential solutions, below: 

1. https://github.com/nodeconf/budapest/issues/70 
https://redom.js.org/ - Redom js view rendering library see: 'works on server-side as well' (at bottom of page)
 
2. Fake the DOM using jsdom as per here - https://github.com/vuejs/vue-hackernews-2.0/issues/52 

3. The pattern demonstrated in this article - http://ryandao.net/reactjs-server-side-rendering-with-browser-dependencies/ 

4. http://stackoverflow.com/questions/38951721/react-js-server-side-issue-window-not-found - this 'hack'

5. https://medium.com/@pimterry/building-a-server-rendered-map-component-part-2-using-client-side-libraries-6f1bb751f31c#.75pc3g8x5 - 'emulating the expected dom' 

6. https://www.smashingmagazine.com/2016/03/server-side-rendering-react-node-express/ 

7. https://github.com/purposeindustries/window-or-global - library for providing window/document/navigator server-side

8. https://github.com/Semantic-Org/Semantic-UI-React/pull/824 - semantic-ui-react pull request addresssing the issue

**Comment by Extra-lightwill** [comment]
The following approach seems to crop up quite a lot: http://josdejong.com/blog/2015/03/28/a-broader-view-on-isomorphic-javascript/ (code from article below)
 
```
if (typeof window !== 'undefined') {
//client-side code 
}
else 
{ 
//node.js
}
```

************************
you can also find it in facebook's js library

```
const canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```
source: (https://github.com/facebook/fbjs/blob/e66ba20ad5be433eb54423f2b097d829324d9de6/packages/fbjs/src/core/ExecutionEnvironment.js#L14)

**Example usage from other isomorphic boilerplates** 

https://github.com/paypal/react-engine/blob/7014459e1109240aabba21a708434677ff9c7583/lib/client.js#L24

https://github.com/shakacode/react_on_rails/blob/1ea99d97463a140a4fd8411c9fdd8e85921fc55a/node_package/src/clientStartup.js#L12

https://github.com/NiallBrickell/particles-on-map/blob/88820aabbec8e91dac43439612075731c11a6d13/dist/bundle.js#L8725

********************
@thelordoftheboards let me know what you think, whether it can actually solve the issue and where this pattern might best be integrated into URB (this is pretty new territory for me)?

**Comment by thelordoftheboards** [comment]
This could work pretty well, I do not see why not. Please notice that as is, global.window is set in `renderOnServer.js` for use in `withWidth.js` so that part of the code might need to be modified somehow. In general, though, I do not see why the approach could not work. I think the more comprehensive

```js
const canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```

Should work.

**Comment by Extra-lightwill** [comment]
Great to hear! How exactly would you go about implementing it?

**Comment by thelordoftheboards** [comment]
I would try to simply exclude the rendering of the component on the server. Of course, when react re-renders on the client, it would find that the check sum is different and replace your entire DOM, but that might be an OK thing depending on your scenario.

**Comment by Extra-lightwill** [comment]
@thelordoftheboards So you're suggesting doing it on a case-by-case basis rather than globally? For example, I could do something like (see code below) but having to adapt/refactor external libraries could become tiresome in the long-run, don't you think?  

```
import React, { PropTypes, Component } from 'react';
import styles from './ContactPage.scss';
import withStyles from '../../decorators/withStyles';
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

@withStyles(styles)
class ContactPage extends Component {

  static contextTypes = {
    onSetTitle: PropTypes.func.isRequired,
  };

  render() {
    const title = 'Contact Us';
    this.context.onSetTitle(title);
    **if (canUseDOM) {**
      const AceEditor = require('react-ace')
      return (
        <div className="ContactPage">
          <div className="ContactPage-container">
            <h1>{title}</h1>
            <p>...</p>
            <AceEditor
              mode="java"
              theme="github"
              name="UNIQUE_ID_OF_DIV"
              editorProps={{$blockScrolling: true}}
            />
          </div>
        </div>
      );
    }
    else {
      return (
        <div className="ContactPage">
          <div className="ContactPage-container">
            <h1>{title}</h1>
            <p>...</p>
          </div>
        </div>
      );
    }
  }

}

export default ContactPage;
```

I guess the above is similar to what you were trying to do with the Graphiql editor and I'm basically, asking, would your solution be to refactor the library manually? I don't know if there is a effective way to do this 'globally' so all cases would be caught and dealt with accordingly but I'm assuming it would look something like the following: https://github.com/akiran/react-isomorphic-example/blob/e649a9929cb7d1ff9029c015b54260472bd885fa/client/app.jsx#L39

If you have time to provide a detailed code example of how and where can I implement this pattern so it is effective globally in URB that would really help! Thanks.

**Comment by Extra-lightwill** [comment]
@thelordoftheboards Imported jsdom and added the below to renderOnServer and deleted the other reference to window object (I'm using a different approach to layout so this wasn't necessary). 

```
//fakeDOM
          global.document = jsdom('');
          global.window = document.defaultView; 
```

Whether this is a viable solution performance-wise, I have no idea - I'd have to look into it.

**Comment by thelordoftheboards** [comment]
@Extra-lightwill I like this solution, if there aren't too many performance complications it would be good to baseline. Definitely having one standard solution would be better than a case by case handling of 

```js
if (canUseDOM) {
      const AceEditor = require('react-ace')
      return (
        <div className="ContactPage">
          <div className="ContactPage-container">
            <h1>{title}</h1>
            <p>...</p>
            <AceEditor
              mode="java"
              theme="github"
              name="UNIQUE_ID_OF_DIV"
              editorProps={{$blockScrolling: true}}
            />
          </div>
        </div>
      );
    }
```

Does it happen to break anything else, like the isomorphic variables, or width detection, for instance?

**Comment by Extra-lightwill** [comment]
@thelordoftheboards I will look into it..

**Comment by thelordoftheboards** [comment]
@Extra-lightwill if you have something that is working and performing decently well, please PR. I believe that it can be a useful baseline functionality.

**Comment by thelordoftheboards** [comment]
@Extra-lightwill  did you find a solution that suits your needs?

**Comment by thelordoftheboards** [comment]
@Extra-lightwill at this point I will close the issue because of inactivity. If you decide to work on this, please reopen or create a new one.
