### ISSUE TITLE
Error while running the dev server

### ISSUE THREAD

**Issue by sudheerj** [codefoundries/UniversalRelayBoilerplate#283]
When I try to run "yarn dev" command then i got below error

> 
> [1] C:\users\sjonna\git\UniversalRelayBoilerplate\node_modules\babel-polyfill\lib\index.js:10
> [1]   throw new Error("only one instance of babel-polyfill is allowed");
> [1]   ^
> [1]
> [1] Error: only one instance of babel-polyfill is allowed
> [1]     at Object.<anonymous> (C:\users\sjonna\git\UniversalRelayBoilerplate\node_modules\babel-polyfill\lib\index.js:10:9)

Is there any clue why babel-polyfill trying to load multiple times?

**Comment by thelordoftheboards** [comment]
Have not seen that happen before. Could it be, by any chance, a conflict with a globally installed babel?

**Comment by sudheerj** [comment]
After commenting out babel-polyfill import from server.js then it works properly.Thanks.
