### ISSUE TITLE
[server] Add support for MySQL persistence.

### ISSUE THREAD

**Issue by robrobkay51** [codefoundries/UniversalRelayBoilerplate#284]
I want to integrate this boilerplate with MySQL (or Postgres) - would this be the best choice https://github.com/mickhansen/graphql-sequelize /will there be any issues given the current setup?

**Comment by thelordoftheboards** [comment]
The boiler plate has, to some extent, the capability of working with multiple databases, including working with only one database of a SQL kind. However, it is not implemented.

All database access is implemented using the persister units:

* [urb-persister-cassandra](https://github.com/codefoundries/UniversalRelayBoilerplate/tree/master/units/urb-persister-cassandra).
* [urb-persister-dynamodb](https://github.com/codefoundries/UniversalRelayBoilerplate/tree/master/units/urb-persister-dynamodb).
* [urb-persister-memory](https://github.com/codefoundries/UniversalRelayBoilerplate/tree/master/units/urb-persister-memory).

In theory, adding additional persisters, as long as they provide the same API, should allow for using other databases. I had a plan to implement waterline, which would support MySQL too, but had no time to actually work on it:

* [urb-persister-waterline](https://github.com/codefoundries/UniversalRelayBoilerplate/tree/master/units/urb-persister-waterline).

Keep in mind that all persisters would be using data loader, and in the case of MySQL there are some optimizations to be made. Please review [Using DataLoader to batch requests](http://gajus.com/blog/9/using-dataloader-to-batch-requests).

If you achieve a working persister unit working with MqSQL, whatever technology it uses underneath, please feel free to PR.

**Comment by thelordoftheboards** [comment]
Since this will most probably be handled by waterline I am closing the issue: https://github.com/codefoundries/UniversalRelayBoilerplate/issues/222
