### ISSUE TITLE
[webapp] Best way to make all routes only accessible after login

### ISSUE THREAD

**Issue by querl** [codefoundries/UniversalRelayBoilerplate#290]
thanks for your hard work her! small question: whats the best way to make a webapp, whree all pages are only accessible after successfull login (execpt landing page, login..)?

**Comment by thelordoftheboards** [comment]
@querl thank you for the kind words. Have you looked at https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/units/urb-example-force-login/webapp/components/ForceLogin.js ? Or you have something else in mind?

**Comment by querl** [comment]
@thelordoftheboards Thanks for the quick response. Yes, I'm using this system currently in the render() function in a custom version of  https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/webapp/components/Chrome.jsx to protect all child components. But I'm not sure if there is a better way to handle this in https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/webapp/renderOnServer.js. 

If no user token is found (anonymous user) the user should always be redirected to a login user page.

**Comment by thelordoftheboards** [comment]
@querl Maybe it is possible to add a property to the routes indicating if they require log in? Even more so, there could maybe be a function that checks what permissions does the user have for each route, if we are to support user roles.

**Comment by querl** [comment]
@thelordoftheboards  Yes thanks, you are right. The react-router onEnter Hook seems a pretty good solution to handle auth and role based access. https://github.com/ReactTraining/react-router/blob/v3/docs/Glossary.md#enterhook

**Comment by thelordoftheboards** [comment]
If you would like to PR with a solution that does not break the existing functionality, I would love to merge it.

**Comment by thelordoftheboards** [comment]
Security and navigation will be revamped, if there are issues afterward, this can be re-opened.
