### ISSUE TITLE
[live demo] demo is broken

### ISSUE THREAD

**Issue by phra** [codefoundries/UniversalRelayBoilerplate#291]
hi,

i was trying to see the [live demo](https://universal-relay-boilerplate.herokuapp.com/), but it's broken.
![immagine](https://cloud.githubusercontent.com/assets/984628/25049996/eb6003b2-2144-11e7-8a1a-8c7453f9f249.png)

**Comment by thelordoftheboards** [comment]
I will have to look into this again. Can't quite figure it out yet :(

**Comment by thelordoftheboards** [comment]
There seems a problem with bcrypt on heroku. I do not believe this can be resolved easily. I will be looking into AWS hosting.

**Comment by thelordoftheboards** [comment]
@phra bcryptjs might indeed be an elegant way around it, although it does reduce the performance with 30%.

**Comment by phra** [comment]
@thelordoftheboards you can create a separate branch for the online demo with bcryptjs and keep on master the native one.

**Comment by thelordoftheboards** [comment]
@phra this is an interesting idea, I should give it a try!

**Comment by thelordoftheboards** [comment]
@phra Simple replacement with bcryptjs did not do the job.

**Comment by phra** [comment]
which is the actual error?

**Comment by thelordoftheboards** [comment]
I followed the instructions in: https://github.com/heroku/heroku-buildpack-nodejs/issues/337#issuecomment-255095490
and it worked
