### ISSUE TITLE
[global] Windows support?

### ISSUE THREAD

**Issue by hubert-associates** [codefoundries/UniversalRelayBoilerplate#298]
Following instructions gives errors on windows 10. This is probably not a surprise. Too bad.

**Comment by thelordoftheboards** [comment]
Unfortunately we do not have the resources to test on windows. People had good luck with running the project for the web and react native parts on windows in the past. It is possible that later changes, or newer versions of windows, have broken that capability. Windows versions of scripts are located in [urb-tools-windows](https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/units/urb-tools-windows/package.part.json). Will happily merge PR enabling/fixing/extending windows support.

**Comment by hubert-associates** [comment]
Thanks. That helps.
