### ISSUE TITLE
Provide better mechanism to access /graphql

### ISSUE THREAD

**Issue by justinr1234** [codefoundries/UniversalRelayBoilerplate#4]
Right now you have to download an addon such as https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en

In order to add "user_auth_token" to be able to access graphiql. It should have some sort of authentication mechanism that works better.

**Comment by thelordoftheboards** [comment]
I agree. At some point I experimented with embedding the GraphiQL component in the application, but the ACE editor it uses would not render on server.
I will also need to look how to handle the authentication on mobile, whatever solution I can find will hopefully satisfy both.
