### ISSUE TITLE
Upgrade to withWidth HOC

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#43]
https://github.com/callemall/material-ui/pull/4126

**Comment by thelordoftheboards** [comment]
![image](https://cloud.githubusercontent.com/assets/7056535/15084309/8604ede6-1387-11e6-81c4-271a752cddac.png)

**Comment by wtgtybhertgeghgtwtg** [comment]
Isn't this just a matter of replacing the current FullWidthSection.jsx with the FullWidthSection.js from the material-ui docs and updating the references to change the file extension?  I can try and file a PR for this if you aren't working on it.

**Comment by thelordoftheboards** [comment]
I am not completely sure what the new approach is. According to https://github.com/callemall/material-ui/pull/4126 `withWidth` should be used but it was not available in the beta.
I am not working on this at the moment, and I could definitely use help. I definitely recommend checking out the MUI documentation site, since this is where the code is pretty much lifted from:

https://github.com/callemall/material-ui/blob/master/docs/src/app/components/Master.js

They seem to be using `withWidth` but it was not available in the beta, I'd assume it is included by now.

**Comment by thelordoftheboards** [comment]
I checked the implementation on the documentation site, and it is using withWidth. I will go with that version.
