### ISSUE TITLE
Problem with yarn setup-local

### ISSUE THREAD

**Issue by FlopiVG** [codefoundries/UniversalRelayBoilerplate#445]
I clone this proyect, install dependencies and when i try to use setup-local throw me an error.

Looks like you installed react-native globally, maybe you meant react-native-cli
?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
error Command failed with exit code 1.

I only have installed react-native-cli globally, i try to uininstall react-native and install react-native-cli but have the same error

Node v8.6.0
Yarn 1.2.1

**Comment by thelordoftheboards** [comment]
Un fortunately at this point the react native parts have not been transferred from the old boilerplate. At this point in time it is ready only for the web part. I am hoping to be able to get back to porting the RN parts from the previous version early next year.

**Comment by thelordoftheboards** [comment]
I tested the setup from scratch with node `8.9.1` and yarn `1.3.2` and works like a charm on MacOS . I would assume it was some kind of transient issue with node or yarn. I will close the issue, if it appears again with the new versions please re-open. Also, please provide the specific errors you are receiving.
