### ISSUE TITLE
Update the comments to state that the use of GLOBAL in renderOnServer is a OK

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#6]
in `renderOnServer.js` the following is done:

```javascript
          // Setting up static, global navigator object to pass user agent to material-ui. Previously
          // this was protected by the queue but is this legal now? Consult with new MUI
          // documentation.
          GLOBAL.navigator = { userAgent: req.headers[ 'user-agent' ] };

          // Setting up static, global location for the leftNav
          GLOBAL.location = { pathname: req.originalUrl };
```

In a previous version this was in a queue, but how should it be approached now?

**Comment by joonhocho** [comment]
Why are these necessary in the first place?
Are they required by relay?

**Comment by thelordoftheboards** [comment]
Relay does not require GLOBAL.
It is required currently to pass the navigator to MUI during server rendering:
https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/webapp/components/Chrome.jsx

```javascript
class Chrome extends React.Component
{
  constructor( props )
  {
    super( props );

    this.state = {
      navDrawerOpen: false,
    };

    this.muiTheme = getMuiTheme(
      muiTheme,
      { userAgent: navigator.userAgent }
    )
  }
```

My plan is to pass it to the component instead of setting it as global. What do you think, any better ideas?

**Comment by joonhocho** [comment]
Yeah, I agree that it should be passed as props.
Avoiding usage of globals is almost always better choice in terms of easier testing and avoiding problems like this.

**Comment by joonhocho** [comment]
If it's used everywhere and deep down in the component tree, then I think you can consider using context though it is generally not recommended. https://facebook.github.io/react/docs/context.html

**Comment by thelordoftheboards** [comment]
The MUI theme is already in the context as per MUI recommendations:

```javascript
  getChildContext( )
  {
    return ( {
      muiTheme: this.muiTheme
    } );
  }
```

**Comment by joonhocho** [comment]
Wait, looking at the source, renderOnServer.js.
It seems that the `render` is synchronous function. If it is synchronous, then I see no problem with the current usage of `GLOBAL`.

**Comment by thelordoftheboards** [comment]
Good point! I was overthinking it! I will close the issue and update the comments in the code. You saved me some unnecessary effort and making the code uglier for nothing :)
