### ISSUE TITLE
[app] Implement react-router-scroll

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#78]
Consider whether to implement it or not. Seems straightforward and can be useful.

https://github.com/denvned/isomorphic-relay-router/issues/30#issuecomment-219903534

**Comment by rajinwonderland** [comment]
https://medium.com/chop-technologies/fast-and-fluid-infinite-list-with-react-native-336d010e51f2#.d9w0d0hbf

**Comment by thelordoftheboards** [comment]
RN client currently removed. Can be re-opened when the RN client is re-introduced.
