### ISSUE TITLE
Upgrade to Material-UI 0.15

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#9]

**Comment by thelordoftheboards** [comment]
Upgrade to beta 2 is pretty much complete, barring any bugs found

**Comment by oliviertassinari** [comment]
Notice that we will soon do the release.

**Comment by thelordoftheboards** [comment]
Thank you for the notice. I will be watching out for it. By now I have made all the changes related to naming and component modification that I am aware of. There are also couple of bugs that are occurring, which might be MUI, React, or Relay related (I had to update all 3 at the same time) that I am looking into.

**Comment by thelordoftheboards** [comment]
@oliviertassinari thank you and the rest of the team, I am loving it!
